### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by JunioCalu** [svt/bridge#45]
Debugging from ubuntu 22.04 server:

ubuntu@ip:~/bridge$ docker compose build --no-cache
[+] Building 47.9s (9/11)                                                                                                                             
 => [app internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 382B                                                                                                             0.0s
 => [app internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 44B                                                                                                                 0.0s
 => [app internal] load metadata for docker.io/library/node:14.16.0-alpine3.10                                                                   0.3s
 => [app stage-0 1/6] FROM docker.io/library/node:14.16.0-alpine3.10@sha256:a9c1dca1d75c99119323a8487e2b8ecaf5c6314e58c4838c6f046e24f95bc5ea     0.0s
 => CACHED [app stage-0 2/6] WORKDIR /app                                                                                                        0.0s
 => [app internal] load build context                                                                                                            0.1s
 => => transferring context: 24.30kB                                                                                                             0.1s
 => [app stage-0 3/6] COPY package*.json ./                                                                                                      0.1s
 => [app stage-0 4/6] RUN npm ci                                                                                                                28.8s
 => [app stage-0 5/6] COPY . ./                                                                                                                  0.7s
 => [app stage-0 6/6] RUN npm run build                                                                                                         17.8s 
 => => # npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                           
 => => # npm ERR! A complete log of this run can be found in:                                                                                         
 => => # npm ERR!     /root/.npm/_logs/2023-07-22T12_51_57_601Z-debug.log                                                                             
 => => # Browserslist: caniuse-lite is outdated. Please run:                                                                                          
 => => #   npx browserslist@latest --update-db                                                                                                       
 => => #   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

**Comment by axelboberg** [comment]
Hi,

Bridge has not yet seen its first release so build errors are to be expected. However, if you want to try out the current master branch you should run it directly in Electron, using one of the `electron` commands found in package.json, **after** building the frontend.
